using System.Runtime.InteropServices;
using System.Text;
using Silk.NET.Shaderc;

namespace Ignis.ShaderCompiler;

internal static class Program
{
    private static readonly System.Text.Json.JsonSerializerOptions _jsonOptions = new() { WriteIndented = true };

    private static unsafe int Main(string[] args)
    {
        bool force = args.Contains("--force");
        string? projectDirRaw = args.FirstOrDefault(a => !a.StartsWith("--", StringComparison.Ordinal));

        if (string.IsNullOrEmpty(projectDirRaw))
        {
            Console.WriteLine("Использование: Ignis.ShaderCompiler <путь_к_проекту> [--force]");
            return 1;
        }

        string projectDir = Path.GetFullPath(projectDirRaw);
        string shadersDir = Path.Combine(projectDir, "Shaders");

        if (!Directory.Exists(shadersDir))
        {
            Console.WriteLine($"Папка shaders не найдена: {shadersDir}");
            return 0;
        }

        string outputDir = Path.Combine(projectDir, "Graphics");
        string outputPath = Path.Combine(outputDir, "Shaders.g.cs");
        string cachePath = Path.Combine(outputDir, ".shader_cache.json");

        // Находим все файлы .task, .mesh и .frag
        string[] taskFiles = Directory.GetFiles(shadersDir, "*.task");
        string[] meshFiles = Directory.GetFiles(shadersDir, "*.mesh");
        string[] fragFiles = Directory.GetFiles(shadersDir, "*.frag");

        if (taskFiles.Length == 0 && meshFiles.Length == 0 && fragFiles.Length == 0)
        {
            Console.WriteLine("Нет файлов шейдеров для компиляции.");
            return 0;
        }

        // Проверяем кэш хешей
        Dictionary<string, string> oldCache = [];
        if (File.Exists(cachePath))
        {
            try
            {
                string json = File.ReadAllText(cachePath);
                oldCache = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(json) ?? [];
            }
            catch (System.Text.Json.JsonException)
            {
                // Игнорируем ошибку чтения битого кэша
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
        }

        bool anyChanged = force || !File.Exists(outputPath) || !File.Exists(cachePath);
        Dictionary<string, string> currentHashes = [];

        var allShaderFiles = taskFiles.Concat(meshFiles).Concat(fragFiles).ToArray();
        foreach (var file in allShaderFiles)
        {
            string name = Path.GetFileName(file);
            string hash = ComputeHash(file);
            currentHashes[name] = hash;

            if (!oldCache.TryGetValue(name, out var oldHash) || oldHash != hash)
            {
                anyChanged = true;
            }
        }

        if (oldCache.Count != currentHashes.Count)
        {
            anyChanged = true;
        }

        if (!anyChanged)
        {
            Console.WriteLine("Шейдеры не изменились, пропуск компиляции.");
            return 0;
        }

        Shaderc shaderc = Shaderc.GetApi();
        Compiler* compiler = shaderc.CompilerInitialize();
        CompileOptions* options = shaderc.CompileOptionsInitialize();
        // Настраиваем компилятор на Vulkan 1.3 для поддержки Mesh-шейдеров
        shaderc.CompileOptionsSetSourceLanguage(options, SourceLanguage.Glsl);
        shaderc.CompileOptionsSetTargetEnv(options, TargetEnv.Vulkan, (uint)EnvVersion.Vulkan13);

        try
        {
            StringBuilder codeBuilder = new();
            codeBuilder.AppendLine("// <auto-generated />");
            codeBuilder.AppendLine("using System;");
            codeBuilder.AppendLine();
            codeBuilder.AppendLine("namespace Ignis.Platform.Graphics;");
            codeBuilder.AppendLine();
            codeBuilder.AppendLine("internal static class Shaders");
            codeBuilder.AppendLine("{");

            bool first = true;

            void CompileShader(string filePath, ShaderKind kind)
            {
                string fileName = Path.GetFileName(filePath);
                string varName = fileName.Replace('.', '_').ToUpperInvariant();

                Console.WriteLine($"Компиляция {fileName}...");

                string sourceCode = File.ReadAllText(filePath);
                byte[] sourceBytes = Encoding.UTF8.GetBytes(sourceCode);

                nint pFileName = Marshal.StringToCoTaskMemUTF8(fileName);
                nint pEntryPoint = Marshal.StringToCoTaskMemUTF8("main");

                CompilationResult* result;
                fixed (byte* pSource = sourceBytes)
                {
                    result = shaderc.CompileIntoSpv(
                        compiler, 
                        pSource, 
                        (nuint)sourceBytes.Length, 
                        kind, 
                        (byte*)pFileName, 
                        (byte*)pEntryPoint, 
                        options);
                }

                Marshal.FreeCoTaskMem(pFileName);
                Marshal.FreeCoTaskMem(pEntryPoint);

                if (result == null)
                {
                    throw new InvalidOperationException($"Ошибка компиляции {fileName}: нулевой указатель результата.");
                }

                CompilationStatus status = shaderc.ResultGetCompilationStatus(result);
                if (status != CompilationStatus.Success)
                {
                    string error = Marshal.PtrToStringUTF8((nint)shaderc.ResultGetErrorMessage(result)) ?? "Неизвестная ошибка";
                    shaderc.ResultRelease(result);
                    throw new InvalidOperationException($"Ошибка компиляции {fileName}:\n{error}");
                }

                nuint length = shaderc.ResultGetLength(result);
                byte* bytesPtr = shaderc.ResultGetBytes(result);

                byte[] compiledBytes = new byte[length];
                Marshal.Copy((nint)bytesPtr, compiledBytes, 0, (int)length);
                shaderc.ResultRelease(result);

                if (!first)
                    codeBuilder.AppendLine();
                first = false;

                codeBuilder.AppendLine(System.Globalization.CultureInfo.InvariantCulture, $"    internal static ReadOnlySpan<byte> {varName} => new byte[{compiledBytes.Length}]");
                codeBuilder.AppendLine("    {");

                StringBuilder lineBuilder = new();
                lineBuilder.Append("        ");
                for (int i = 0; i < compiledBytes.Length; i++)
                {
                    lineBuilder.Append(System.Globalization.CultureInfo.InvariantCulture, $"0x{compiledBytes[i]:X2}");
                    if (i < compiledBytes.Length - 1)
                    {
                        lineBuilder.Append(", ");
                    }

                    if (lineBuilder.Length > 100 || i == compiledBytes.Length - 1)
                    {
                        codeBuilder.AppendLine(lineBuilder.ToString());
                        lineBuilder.Clear();
                        if (i < compiledBytes.Length - 1)
                        {
                            lineBuilder.Append("        ");
                        }
                    }
                }

                codeBuilder.AppendLine("    };");
            }

            foreach (var taskFile in taskFiles)
            {
                CompileShader(taskFile, ShaderKind.TaskShader);
            }

            foreach (var meshFile in meshFiles)
            {
                CompileShader(meshFile, ShaderKind.MeshShader);
            }

            foreach (var fragFile in fragFiles)
            {
                CompileShader(fragFile, ShaderKind.FragmentShader);
            }

            codeBuilder.AppendLine("}");

            Directory.CreateDirectory(outputDir);
            File.WriteAllText(outputPath, codeBuilder.ToString(), Encoding.UTF8);
            Console.WriteLine($"Успешно сгенерирован {outputPath}");

            // Сохраняем обновленный кэш
            string newCacheJson = System.Text.Json.JsonSerializer.Serialize(currentHashes, _jsonOptions);
            File.WriteAllText(cachePath, newCacheJson, Encoding.UTF8);

            return 0;
        }
        catch (InvalidOperationException ex)
        {
            Console.WriteLine($"Ошибка при компиляции шейдеров: {ex.Message}");
            return 3;
        }
        catch (IOException ex)
        {
            Console.WriteLine($"Ошибка при компиляции шейдеров: {ex.Message}");
            return 3;
        }
        catch (UnauthorizedAccessException ex)
        {
            Console.WriteLine($"Ошибка при компиляции шейдеров: {ex.Message}");
            return 3;
        }
        finally
        {
            shaderc.CompileOptionsRelease(options);
            shaderc.CompilerRelease(compiler);
        }
    }

    private static string ComputeHash(string filePath)
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        using var stream = File.OpenRead(filePath);
        byte[] hashBytes = sha.ComputeHash(stream);
        return Convert.ToHexString(hashBytes).ToUpperInvariant();
    }
}
